
const val PLAYER_SELF = 0
const val PLAYER_OTHER = 1
const val MAX_NUMBER_OF_AFFECTED_TARGETS = 2
const val NUMBER_OF_PARAM_TARGETS = 2

// member properties
const val REFLECTION_ENDURANCE = 1 // 0
const val PLAYER_STAT_ENDURANCE = REFLECTION_ENDURANCE
const val REFLECTION_STATS = 4

// member properties of PlayerStats
const val PLAYER_STATS_SHIFT = 1;

const val REFLECTION_COORDINATION = 0
const val REFLECTION_PERSISTENCE = 1
const val REFLECTION_REACTION = 2
const val REFLECTION_STRENGTH = 3
const val REFLECTION_WILL = 4

const val PLAYER_STAT_COORDINATION = PLAYER_STATS_SHIFT + REFLECTION_COORDINATION
const val PLAYER_STAT_PERSISTENCE = PLAYER_STATS_SHIFT + REFLECTION_PERSISTENCE
const val PLAYER_STAT_REACTION = PLAYER_STATS_SHIFT + REFLECTION_REACTION
const val PLAYER_STAT_STRENGTH = PLAYER_STATS_SHIFT + REFLECTION_STRENGTH
const val PLAYER_STAT_WILL = PLAYER_STATS_SHIFT + REFLECTION_WILL

val PLAYER_STATS_MEMBERS = listOf(REFLECTION_COORDINATION, REFLECTION_PERSISTENCE, REFLECTION_REACTION,
        REFLECTION_STRENGTH, REFLECTION_WILL) // 1-5

// functions
const val PLAYER_FUNCTIONS_SHIFT = 6;
const val REFLECTION_ARMOUR = 0
const val REFLECTION_EVASION = 1
const val REFLECTION_FORTITUDE = 2
const val REFLECTION_PARRY = 3
const val REFLECTION_SPEED = 4
const val REFLECTION_STAMINA = 5

const val PLAYER_STAT_ARMOUR = PLAYER_FUNCTIONS_SHIFT + REFLECTION_ARMOUR
const val PLAYER_STAT_EVASION = PLAYER_FUNCTIONS_SHIFT + REFLECTION_EVASION
const val PLAYER_STAT_FORTITUDE = PLAYER_FUNCTIONS_SHIFT + REFLECTION_FORTITUDE
const val PLAYER_STAT_PARRY = PLAYER_FUNCTIONS_SHIFT + REFLECTION_PARRY
const val PLAYER_STAT_SPEED = PLAYER_FUNCTIONS_SHIFT + REFLECTION_SPEED
const val PLAYER_STAT_STAMINA = PLAYER_FUNCTIONS_SHIFT + REFLECTION_STAMINA

val PLAYER_FUNCTIONS = listOf(REFLECTION_ARMOUR, REFLECTION_EVASION, REFLECTION_FORTITUDE, REFLECTION_PARRY,
        REFLECTION_SPEED, REFLECTION_STAMINA) // 6-11
